// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llqunjamfzknowdzqqkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscXVuamFtZnprbm93ZHpxcWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzU1NzEsImV4cCI6MjA2NDkxMTU3MX0.eoWj7FvdrvfWOdfj-f-P0XmEwaOMBfc-JZlccO__9Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);